Repository actorcloud/ActorCloud, pull requests merged in 2019-07, with the labels that each got.

#306 fix(store): fix local language only supports zh and en
  ui/src/apps/accounts/store.js
Labels: ui

#307 fix(charts): fix custom chart with deviceID as key
  ui/src/apps/devices/components/ClientsCharts.vue
  ui/src/apps/devices/views/DeviceDetailsCharts.vue
Labels: ui

#309 style(mqtt_client): fix mqtt-client info height
  ui/src/apps/devices/lang/en.js
  ui/src/apps/test-center/lang/en.js
  ui/src/apps/test-center/views/MQTTClient.vue
  ui/src/lang/en.js
Labels: ui

#308 fix(stream): fix record ack error
  rule-engine/actorcloud-db-sink/src/main/java/io/emqx/pulsar/io/ActorcloudSink.java
  rule-engine/actorcloud-db-sink/src/main/java/io/emqx/pulsar/io/jdbc/JdbcAbstractSink.java
Labels: stream

#312 fix(lang): fix system manager translation
  ui/src/lang/en.js
Labels: ui

#313 fix(rule): add tenant isolation to rule sql
  rule-engine/.gitignore
  server/Pipfile
  server/app/services/rules/schemas.py
Labels: server

#314 fix(geo): fix circle distance unit error
  rule-engine/rule-function/src/test/java/io/emqx/pulsar/functions/TestRuleFunction.java
  rule-engine/sql/src/main/java/io/emqx/stream/common/GeoUtils.java
Labels: stream

#316 chore(package): upgread dependencies
  ui/package.json
  ui/src/apps/accounts/views/Dashboard.vue
  ui/src/apps/rules/components/LocationScopeEditDialog.vue
  ui/src/assets/scss/reset.scss
  ui/yarn.lock
Labels: ui

#315 feat(log): add backend log
  server/actor_libs/http_tools/async_http.py
  server/actor_libs/http_tools/sync_http.py
  server/actor_libs/logs.py
  server/app/__init__.py
  server/app/services/devices/views/devices.py
  server/app/services/products/views/codec.py
  server/app/services/publish/views/devices.py
  server/app/services/rules/schemas.py
  server/app/services/rules/views/rules.py
  server/app/services/tasks_scheduler/async_tasks/app/emqx/callback.py
  server/app/services/tasks_scheduler/async_tasks/app/emqx/sql_statements.py
  server/config/config.yml
Labels: server

#317 fix(rules): modify the rules sql stitching
  ui/src/apps/rules/components/TopicForm.vue
  ui/src/apps/rules/views/ScopeRuleDetails.vue
Labels: ui

#318 migrate the codec to actorcloud-docker
  deploy/README.md
  server/Pipfile
  server/app/services/codec/Dockerfile
  server/app/services/codec/README.md
  server/app/services/codec/__init__.py
  server/app/services/codec/codec.conf
  server/app/services/codec/codec.py
  server/app/services/codec/gunicorn_codec.py
  server/app/services/codec/sources.list
  server/app/services/codec/start_codec.sh
  server/requirements.txt
Labels: server

#321 test(rule_function): modify and add rule function test cases
  rule-engine/rule-function/src/test/java/io/emqx/pulsar/functions/TestContextWindowFunctionExecutor.java
  rule-engine/rule-function/src/test/java/io/emqx/pulsar/functions/TestRuleFunction.java
Labels: stream

#322 fix(timestamp): error timestamp format conversion
  server/actor_libs/utils.py
  server/app/services/device_data/views/capability_data.py
  server/app/services/device_data/views/charts.py
Labels: server

#323 feat(time): add time util to get current time
  server/config/config.yml
  ui/src/apps/test-center/views/CoAP.vue
  ui/src/apps/test-center/views/MQTTClient.vue
  ui/src/utils/time.js
Labels: ui

#325 fix(create_products): products->product
  ui/src/apps/devices/components/CreateProduct.vue
  ui/src/apps/devices/views/DeviceCreate.vue
Labels: ui

#327 fix(chart): chart data display error
  server/app/services/device_data/views/charts.py
Labels: server

#329 fix(codec): fix codec bug
  server/app/services/products/views/codec.py
Labels: server
